### ISSUE TITLE
Improvement in figure_6_3_TD_methods_performance.py

### ISSUE THREAD

**Issue by Aprilistic** [terrence-ou/Reinforcement-Learning-2nd-Edition-Notes-Codes#1]
Hello!

I think I found a subtle mistake in figure_6_3_TD_methods_performance.py

In line 19, get_expectation has a subtle mistake.
That part is about expected SARSA.
I assume action value of any action should be multiplied by `epsilon / (nA)`

The original code is
```python
def get_expectation(Q: np.ndarray, state: int, epsilon: float):
    # Non greedy actions
    result = (Q[state] * epsilon).sum()
    # Greedy action
    result += Q[state].max() * (1 - epsilon)
    return result
```

And I think we can change like this
```python
def get_expectation(Q: np.ndarray, state: int, epsilon: float):
    nA = Q.shape[-1]
    # Any action
    result = Q[state].sum() * (epsilon / nA)
    # Greedy action
    result += Q[state].max() * (1 - epsilon)
    return result
```

p.s. Thank you so much for sharing your code!! Your code helped me a lot in my studies!

**Comment by terrence-ou** [comment]
Hi, I appreciate you pointing this issue out, and I believe you are absolutely correct. Would you mind creating a PR so that I can merge your change? Thanks!
